create Gallery section
Wollfo/IceCream pull request #1
Opened 2022-09-17 12:53 UTC by Oleh-Kliapko

create Gallery section with one pictures and adaptive layout

2022-09-17 12:57 UTC, Wollfo approved these changes

2022-09-17 13:29 UTC, Wollfo requested changes
Чекаємо на інші секції

2022-09-17 17:14 UTC, Wollfo requested changes
test

2022-09-18 14:02 UTC, Oleh-Kliapko commented
Поправив файли і розмітку

2022-09-18 15:57 UTC, Wollfo approved these changes

2022-09-18 15:58 UTC, merged